apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app-nginx
  template:
    metadata:
      labels:
        app: my-app-nginx
    spec:
      containers:
        - name: my-container
          image: nginx
          ports:
            - containerPort: 80
