name: image and deployment

on:
  workflow_run:
    workflows: ["iac-checks"]   # Debe coincidir EXACTO con el name del otro workflow
    types: [completed]
  #workflow_dispatch: {}          # (Opcional) para dispararlo manualmente

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  image_and_deployment:
    # Solo ejecutar si el workflow previo terminó con éxito
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}   # estandariza nombres
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image
        run: |
          docker build \
            -t rabadiaf/new_image4:latest \
            .

      - name: Push image
        run: docker push rabadiaf/new_image4:latest

      - name: Run Ansible deploy
        run: ansible-playbook -i inventory.ini playbook.yaml

      - name: run terraform
        run: terraform/terraform apply --auto approve
